import type { Track } from '@/types/content';

/**
 * เส้นทางการเรียน 10 เส้น — เส้นละ 10 บท เรียงจากเข้าใจง่ายไปลึก
 *  - 7 เส้นแรกเจาะทีละหมวด (ครบทุกบทของหมวดนั้น)
 *  - 3 เส้นหลังข้ามหมวดตามเป้าหมาย: โปรแกรมเมอร์สู่หัวหน้าทีม / โน้มน้าวและเจรจา / เรียนรู้ให้เร็วและจำนาน
 * บทหนึ่งอยู่ได้หลายเส้น ความคืบหน้านับจากสถานะ "เรียนจบ" ของบทนั้น จึงแชร์กันทุกเส้น
 * ตัวตรวจ: src/content/tracks.test.ts (ทุก id ต้องมีจริง ไม่ซ้ำในเส้นเดียว ครบ 10 บท)
 */
export const TRACKS: Track[] = [
  {
    id: 'china-strategy',
    title: 'กลยุทธ์จีนสำหรับคนยุคนี้',
    subtitle: 'จากซุนวูถึงหานเฟยจื่อ เรียนแบบแยกตำนานออกจากหลักฐาน',
    emoji: '🀄',
    audience: 'ชอบเรื่องเล่าและปรัชญาจีน อยากได้มุมคิดไปใช้กับงานและการเจรจา',
    lessonIds: [
      'a01-sunzi-win-without-fighting',
      'a02-man-tian-guo-hai',
      'a03-borrow-a-knife',
      'a04-wait-at-ease',
      'a05-han-feizi-power-of-position',
      'a06-guiguzi-bai-he',
      'a07-use-of-spies',
      'a09-empty-fort-signaling',
      'a10-liu-bei-vs-cao-cao',
      'a08-wu-wei-leadership',
    ],
  },
  {
    id: 'read-people',
    title: 'อ่านคนให้แม่นขึ้น',
    subtitle: 'ความเอนเอียงที่ทำให้เราอ่านคนพลาด และเครื่องมือที่ช่วยได้จริง',
    emoji: '🔍',
    audience: 'อยากเข้าใจคนมากขึ้น และไม่ตกเป็นเหยื่อของความประทับใจแรก',
    lessonIds: [
      'b01-thin-slicing',
      'b02-fundamental-attribution-error',
      'b04-spotlight-effect',
      'b05-halo-effect',
      'b08-barnum-effect',
      'b03-lie-detection-myth',
      'b06-perspective-getting',
      'b09-power-pose-replication',
      'b07-cialdini-six-levers',
      'b10-dark-triad',
    ],
  },
  {
    id: 'people-mgmt',
    title: 'ผู้จัดการที่ทีมอยากทำงานด้วย',
    subtitle: 'ความปลอดภัยทางจิตใจ feedback การมอบหมาย และการสร้างแรงจูงใจ',
    emoji: '👥',
    audience: 'หัวหน้าทีมหรือคนที่กำลังจะเป็น อยากบริหารคนด้วยหลักฐานมากกว่าความเชื่อ',
    lessonIds: [
      'c01-psychological-safety-project-aristotle',
      'c03-effective-one-on-one',
      'c02-radical-candor',
      'c04-feedback-intervention-theory',
      'c06-goal-setting',
      'c09-social-loafing',
      'c05-delegation-levels',
      'c07-autonomy-mastery-purpose',
      'c08-structured-interviews',
      'c10-task-vs-relationship-conflict',
    ],
  },
  {
    id: 'relationships',
    title: 'ความสัมพันธ์และการเริ่มบทสนทนา',
    subtitle: 'จากความคุ้นเคยถึงการถามต่อ ด้วยหลักฐานและความเคารพ',
    emoji: '💬',
    audience: 'อยากสร้างและรักษาความสัมพันธ์ โดยไม่พึ่งเทคนิคหลอกล่อ',
    lessonIds: [
      'd01-mere-exposure-effect',
      'd05-similarity-not-opposites',
      'd08-liking-gap',
      'd10-ask-follow-up-questions',
      'd06-36-questions',
      'd04-bids-for-connection',
      'd02-gottman-four-horsemen',
      'd03-attachment-styles-not-destiny',
      'd07-misattribution-of-arousal',
      'd09-online-dating-science',
    ],
  },
  {
    id: 'brain',
    title: 'สมองและการเรียนรู้',
    subtitle: 'ความจำ สมาธิ การนอน และตำนานที่ควรเลิกเชื่อ',
    emoji: '🧠',
    audience: 'อยากเข้าใจวิธีที่สมองทำงาน เพื่อเรียนรู้และใช้สมองให้คุ้ม',
    lessonIds: [
      'e01-testing-effect-myth',
      'e03-spacing-effect',
      'e02-sleep-memory-consolidation',
      'e04-multitasking-myth',
      'e06-learning-styles-myth',
      'e08-london-taxi-neuroplasticity',
      'e09-working-memory-limits',
      'e05-exercise-and-brain',
      'e07-mind-wandering',
      'e10-false-memory',
    ],
  },
  {
    id: 'self-dev',
    title: 'พัฒนาตัวเองแบบมีหลักฐาน',
    subtitle: 'นิสัย เป้าหมาย ความเมตตาต่อตนเอง และการตัดสินใจ',
    emoji: '🌱',
    audience: 'เบื่อคำแนะนำลอยๆ อยากรู้ว่าอะไรได้ผลจริงและได้ผลแค่ไหน',
    lessonIds: [
      'f01-deliberate-practice-myth',
      'f02-implementation-intentions',
      'f03-habit-66-days',
      'f05-fresh-start-effect',
      'f08-micro-breaks',
      'f06-self-compassion',
      'f10-dichotomy-of-control',
      'f07-three-mental-models',
      'f09-dunning-kruger',
      'f04-growth-mindset-evidence',
    ],
  },
  {
    id: 'dev-career',
    title: 'โปรแกรมเมอร์ที่โตในสายงาน',
    subtitle: 'ทีม โค้ด เวลา และเงินเดือน จากงานวิจัยด้านวิศวกรรมซอฟต์แวร์',
    emoji: '💻',
    audience: 'นักพัฒนาที่อยากเข้าใจว่าทำไมโปรเจกต์และทีมเป็นแบบที่เป็น',
    lessonIds: [
      'g01-dora-metrics',
      'g04-planning-fallacy',
      'g07-interruptions-developers',
      'g08-brooks-law',
      'g10-bus-factor',
      'g03-code-review-evidence',
      'g05-conways-law',
      'g06-tech-debt-as-finance',
      'g02-salary-negotiation',
      'g09-impostor-phenomenon',
    ],
  },
  {
    id: 'dev-to-lead',
    title: 'จากโปรแกรมเมอร์สู่หัวหน้าทีม',
    subtitle: 'ข้ามหมวด: คนผสมทักษะเทคนิคกับการบริหารคน',
    emoji: '🧭',
    audience: 'นักพัฒนาที่กำลังก้าวไปเป็นเทคลีดหรือผู้จัดการ',
    lessonIds: [
      'g08-brooks-law',
      'g04-planning-fallacy',
      'c01-psychological-safety-project-aristotle',
      'c03-effective-one-on-one',
      'c04-feedback-intervention-theory',
      'c05-delegation-levels',
      'g03-code-review-evidence',
      'c06-goal-setting',
      'g05-conways-law',
      'a08-wu-wei-leadership',
    ],
  },
  {
    id: 'persuasion',
    title: 'โน้มน้าวและเจรจาอย่างมีจริยธรรม',
    subtitle: 'ข้ามหมวด: จากกุยกู่จื่อถึงงานวิจัยเรื่องอิทธิพลและการเจรจา',
    emoji: '🤝',
    audience: 'ต้องเจรจา ขอเงินเดือน หรือเสนอไอเดียกับคนอื่นบ่อยๆ และอยากรู้ทันการโน้มน้าว',
    lessonIds: [
      'a06-guiguzi-bai-he',
      'b06-perspective-getting',
      'd10-ask-follow-up-questions',
      'b07-cialdini-six-levers',
      'a07-use-of-spies',
      'g02-salary-negotiation',
      'a09-empty-fort-signaling',
      'b03-lie-detection-myth',
      'b08-barnum-effect',
      'b10-dark-triad',
    ],
  },
  {
    id: 'learn-faster',
    title: 'เรียนรู้ให้เร็วและจำให้นาน',
    subtitle: 'ข้ามหมวด: วิธีเรียนที่มีหลักฐาน และนิสัยที่ทำให้ต่อเนื่อง',
    emoji: '⚡',
    audience: 'ต้องเรียนของใหม่ตลอด ทั้งภาษา เฟรมเวิร์ก และทักษะอาชีพ',
    lessonIds: [
      'e01-testing-effect-myth',
      'e03-spacing-effect',
      'e02-sleep-memory-consolidation',
      'e06-learning-styles-myth',
      'e09-working-memory-limits',
      'e04-multitasking-myth',
      'f01-deliberate-practice-myth',
      'c04-feedback-intervention-theory',
      'f02-implementation-intentions',
      'f03-habit-66-days',
    ],
  },
];

const TRACK_MAP = new Map(TRACKS.map((t) => [t.id, t]));

export function getTrack(id: string): Track | undefined {
  return TRACK_MAP.get(id);
}
